---
  01_broker_primary_ip:
    description: "Primary broker ip-address"
    type: "string"
    required: true
    default: "broker1.localdomain"
    secret: false
  02_broker_primary_username:
    description: "Primary broker account username"
    type: "string"
    default: "admin"
    required: true
  03_broker_primary_authenticator:
      description: "Primary broker authenticator name"
      type: "string"
      default: "authenticator"
      required: true
  04_broker_primary_password:
    description: "Primary broker account password"
    type: "string"
    default: "password"
    secret: true
    required: true
  05_broker_secondary_ip:
    description: "Secondary broker ip-address"
    type: "string"
    required: true
    default: "broker2.localdomain"
    secret: false
  06_broker_secondary_username:
    description: "Secondary broker account username"
    type: "string"
    default: "admin"
    required: true
  07_broker_secondary_authenticator:
      description: "Secondary broker authenticator name"
      type: "string"
      default: "authenticator"
      required: true
  08_broker_secondary_password:
    description: "Secondary broker account password"
    type: "string"
    default: "password"
    secret: true
    required: true
  09_service_pool_name:
    description: "Service pool name on primary broker"
    type: "string"
    default: "ServicePoolName"
    required: true
    secret: false
  10_ovirt_secondary_fqdn:
    description: "oVirt secondary site manager FQND"
    type: "string"
    default: "ovirt2.localdomain"
    required: false
    secret: false
  11_ovirt_secondary_username:
    description: "oVirt secondary site manager username"
    type: "string"
    default: "admin@internal"
    required: false
    secret: false
  12_ovirt_secondary_password:
    description: "oVirt secondary site manager password"
    type: "string"
    default: "password"
    required: false
    secret: true
  13_ovirt_secondary_cluster_uuid:
    description: "oVirt secondary site Cluster UUID"
    type: "string"
    default: ""
    required: false
    secret: false
  14_ovirt_secondary_storagedomain_uuid:
    description: "oVirt secondary site Storage Domain UUID"
    type: "string"
    default: ""
    required: false
    secret: false
  15_ovirt_secondary_golden_vm_uuid:
    description: "Golden image of a virtual machine UUID for the oVirt secondary site"
    type: "string"
    default: ""
    required: false
    secret: false